name = "reap"
defaultTargets = ["Reap"]

[leanOptions]
pp.unicode.fun = true
experimental.module = true

[[require]]
name = "openAI_client"
git = "https://github.com/frenzymath/openai_client.git"
rev = "main"

[[require]]
name = "TreeSearch"
git = "git@github.com:frenzymath/TreeSearch.git"
rev = "feat/option-max-goals"

[[lean_lib]]
name = "Reap"
