name = "reap"
defaultTargets = ["Reap"]

[leanOptions]
pp.unicode.fun = true
experimental.module = true

[[require]]
name = "openAI_client"
git = "https://github.com/frenzymath/openai_client.git"
rev = "main"

[[require]]
name = "aesop"
scope = "leanprover-community"
rev = "master"

[[lean_lib]]
name = "Reap"
